name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Push
        run: |
          docker build . --tag ghcr.io/climateseed/rust-buildpack:latest
          docker run ghcr.io/climateseed/rust-buildpack:latest
          docker push ghcr.io/climateseed/rust-buildpack:latest
